import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="fixed top-0 left-0 right-0 z-50 flex justify-end items-center p-4 gap-4 h-10 bg-transparent pointer-events-none">
            <div className="pointer-events-auto">
              <SignedOut>
                <div className="flex gap-4">
                  <SignInButton />
                  <SignUpButton>
                    <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                      Crear cuenta
                    </button>
                  </SignUpButton>
                </div>
              </SignedOut>
              <SignedIn>
                <div className="flex items-center gap-2 p-5">
                  <UserButton />
                </div>
              </SignedIn>
            </div>
          </header>
          {children}

          {/* <SignedIn>
            {children}
          </SignedIn>
          <SignedOut>
            <AdminLanding />
          </SignedOut> */}

        </body>
      </html>
    </ClerkProvider>
  );
}
